spring:
  sql:
    init:
      mode: always

  application.name: "ShareIt"

  main:
    banner-mode: off

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:5432/shareIt"
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    ru.practicum.shareit: DEBUG
#    logging.level.org.springframework.orm.jpa=INFO
#    logging.level.org.springframework.transaction=INFO
#    logging.level.org.springframework.transaction.interceptor=TRACE
#    logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG